// <auto-generated />
namespace SampleProjectBootStrap.DAL.JobMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initiat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initiat));
        
        string IMigrationMetadata.Id
        {
            get { return "201802211950384_Initiat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
